openapi: 3.0.0
info:
  title: Shopping Cart Order API
  version: 1.0.0
paths:
  /order:
    post:
      summary: Create an order from shopping cart content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: object
                  properties:
                    items:
                      type: array
                      items:
                        type: object
                        properties:
                          productId:
                            type: string
                            format: uuid
                          quantity:
                            type: integer
                            minimum: 1
                          productPrice:
                            type: integer
                            minimum: 1
                  required:
                    - items
                ShipmentDetails:
                  type: object
                  properties:
                    shipmentAddress:
                      type: object
                      properties:
                        country:
                          type: string
                        state:
                          type: string
                        city:
                          type: string
                        addressLine:
                          type: string
                        zipCode:
                          type: string
                        apartment:
                          type: string
                        addressInstructions:
                          type: string
                      required:
                        - country
                        - state
                        - city
                        - addressLine
                        - zipCode
                    shipmentMethod:
                      type: string
                  required:
                    - shipmentAddress
                    - addressInstructions
                    - shipmentMethod
                InvoiceDetails:
                  type: object
                  properties:
                    invoiceAddressIsSameAsShipmentAddress:
                      type: boolean
                    # Additional fields for invoice details
                  required:
                    - invoiceAddressIsSameAsShipmentAddress
                preApprovedPayment:
                  type: object
                  properties:
                    paymentVendor:
                      type: string
                    preApprovedPaymentToken:
                      type: string
                  required:
                    - paymentVendor
                    - preApprovedPaymentToken
      responses:
        '201':
          description: Order created successfully
        '400':
          description: Bad request, check request payload
        '500':
          description: Internal server error, something went wrong